version: '3'

services:
  backend:
    image: 982081055699.dkr.ecr.ap-southeast-1.amazonaws.com/qairline-backend-repo:latest
    container_name: node-backend
    restart: always
    expose:
      - "3030"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    volumes:
      # Đường dẫn này là tương đối từ vị trí của docker-compose.yml (tức là QAirline/backend/)
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
