version: '3'

services:
  backend:
    build:
      context: . # Đường dẫn tới Dockerfile (tức là QAirline/backend/)
      dockerfile: Dockerfile # Tên Dockerfile
    container_name: node-backend
    restart: always
    expose:
      - "3030"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Đường dẫn tương đối từ docker-compose.yml
    ports:
      - "80:80"
    depends_on:
      - backend
