version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/qairline-backend
  - source: /nginx.conf
    destination: /home/ubuntu/qairline-backend/nginx

permissions:
  - object: /home/ubuntu/qairline-backend
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/stop_containers.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 360
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
